In [ ]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 
#(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [20]:
N = int(input())
np.array(sorted(range(N), reverse= True))

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. 
#Посчитайте сумму ее значений на диагонали.

In [40]:
N = int(input())
matrix = np.diag(sorted(range(N), reverse= True))
print(matrix)
total = 0
for i in range(N):
    total += matrix[i][i]
print(total)

6
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


In [ ]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

In [42]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

In [44]:
from numpy import linalg

In [45]:
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [46]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True